pdf('/Volumes/ITDR/brian/results/Acetobacter_pasteurianus/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Acetobacter_pasteurianus/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Acetobacter_pasteurianus")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Acinetobacter_pittii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Acinetobacter_pittii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Acinetobacter_pittii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Bacillus_anthracis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Bacillus_anthracis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Bacillus_anthracis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Bacillus_cereus/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Bacillus_cereus/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Bacillus_cereus")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Bacillus_subtilis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Bacillus_subtilis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Bacillus_subtilis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Bacteroides_fragilis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Bacteroides_fragilis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Bacteroides_fragilis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Brucella_abortus/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Brucella_abortus/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Brucella_abortus")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Brucella_ovis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Brucella_ovis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Brucella_ovis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Burkholderia_cepacia/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Burkholderia_cepacia/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Burkholderia_cepacia")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Burkholderia_stagnalis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Burkholderia_stagnalis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Burkholderia_stagnalis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Burkholderia_ubonensis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Burkholderia_ubonensis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Burkholderia_ubonensis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Chlamydia_trachomatis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Chlamydia_trachomatis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Chlamydia_trachomatis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Citrobacter_freundii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Citrobacter_freundii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Citrobacter_freundii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Clostridium_beijerinckii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Clostridium_beijerinckii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Clostridium_beijerinckii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Clostridium_botulinum/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Clostridium_botulinum/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Clostridium_botulinum")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Cutibacterium_acnes/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Cutibacterium_acnes/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Cutibacterium_acnes")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Gilliamella_apicola/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Gilliamella_apicola/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Gilliamella_apicola")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Haemophilus_influenzae/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Haemophilus_influenzae/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Haemophilus_influenzae")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Klebsiella_michiganensis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Klebsiella_michiganensis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Klebsiella_michiganensis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Klebsiella_oxytoca/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Klebsiella_oxytoca/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Klebsiella_oxytoca")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Klebsiella_quasipneumoniae/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Klebsiella_quasipneumoniae/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Klebsiella_quasipneumoniae")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Klebsiella_variicola/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Klebsiella_variicola/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Klebsiella_variicola")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Lactobacillus_paracasei/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Lactobacillus_paracasei/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Lactobacillus_paracasei")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Lactobacillus_rhamnosus/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Lactobacillus_rhamnosus/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Lactobacillus_rhamnosus")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Lactobacillus_salivarius/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Lactobacillus_salivarius/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Lactobacillus_salivarius")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Leptospira_kirschneri/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Leptospira_kirschneri/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Leptospira_kirschneri")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mannheimia_haemolytica/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mannheimia_haemolytica/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mannheimia_haemolytica")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Methanobrevibacter_smithii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Methanobrevibacter_smithii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Methanobrevibacter_smithii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Micrococcus_luteus/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Micrococcus_luteus/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Micrococcus_luteus")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Microcystis_aeruginosa/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Microcystis_aeruginosa/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Microcystis_aeruginosa")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Moraxella_catarrhalis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Moraxella_catarrhalis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Moraxella_catarrhalis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Morganella_morganii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Morganella_morganii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Morganella_morganii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_africanum/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_africanum/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_africanum")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_bovis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_bovis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_bovis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_chelonae/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_chelonae/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_chelonae")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_colombiense/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_colombiense/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_colombiense")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_fortuitum/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_fortuitum/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_fortuitum")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_immunogenum/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_immunogenum/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_immunogenum")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycobacterium_kansasii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycobacterium_kansasii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycobacterium_kansasii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycoplasma_bovis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycoplasma_bovis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycoplasma_bovis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycoplasma_gallisepticum/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycoplasma_gallisepticum/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycoplasma_gallisepticum")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycoplasma_mycoides/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycoplasma_mycoides/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycoplasma_mycoides")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Mycoplasma_pneumoniae/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Mycoplasma_pneumoniae/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Mycoplasma_pneumoniae")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Porphyromonas_gingivalis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Porphyromonas_gingivalis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Porphyromonas_gingivalis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Prochlorococcus_marinus/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Prochlorococcus_marinus/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Prochlorococcus_marinus")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Propionibacterium_acnes/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Propionibacterium_acnes/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Propionibacterium_acnes")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Propionibacterium_freudenreichii/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Propionibacterium_freudenreichii/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Propionibacterium_freudenreichii")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudoalteromonas_luteoviolacea/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudoalteromonas_luteoviolacea/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudoalteromonas_luteoviolacea")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudomonas_amygdali/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudomonas_amygdali/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudomonas_amygdali")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudomonas_chlororaphis/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudomonas_chlororaphis/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudomonas_chlororaphis")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudomonas_denitrificans/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudomonas_denitrificans/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudomonas_denitrificans")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudomonas_psychrotolerans/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudomonas_psychrotolerans/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudomonas_psychrotolerans")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudomonas_putida/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudomonas_putida/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudomonas_putida")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Pseudomonas_stutzeri/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Pseudomonas_stutzeri/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Pseudomonas_stutzeri")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Raoultella_ornithinolytica/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Raoultella_ornithinolytica/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Raoultella_ornithinolytica")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

pdf('/Volumes/ITDR/brian/results/Rhodococcus_fascians/gno1.pdf')
par(mfrow=c(1,1))
tab = read.table('/Volumes/ITDR/brian/results/Rhodococcus_fascians/graph.txt',h=T)
w=c(tab$Nb,rev(tab$Nb))
v=c(tab$Median-tab$SD,rev(tab$Median + tab$SD))
plot(100,100,cex=0.5,cex.main=0.8,xlim=c(3,max(w)),ylim=c(0,max(v) + 0.1),xlab=c("# Genomes"),ylab=c("h/m"),main="Rhodococcus_fascians")
polygon(w,v,col="gray88",border=NA)
points(tab$Nb,tab$Median,pch=16,cex=0.3,t="b")
dev.off()

dev.off()

